---
name: Tests @ l2-bridge-base

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "l2-bridge-base/**"

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    with:
      path: ./l2-bridge-base
    secrets: inherit
