---
name: Tests @ l2-bridge-mantle

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "l2-bridge-mantle/**"

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    with:
      path: ./l2-bridge-mantle
    secrets: inherit
